### ISSUE TITLE
Error: 'linux-x64' binaries cannot be used on the 'linuxmusl-x64' platform. Please remove the 'node_modules/sharp' directory and run 'npm install' on the 'linuxmusl-x64' platform.

### ISSUE THREAD

**Issue by heoyongun** [onildoaguiar/image-thumbnail#67]
**node version**
v16.4.2

**Error Message**
/usr/app/node_modules/sharp/lib/libvips.js:82
      throw new Error(`'${vendorPlatformId}' binaries cannot be used on the '${currentPlatformId}' platform. Please remove the 'node_modules/sharp' directory and run 'npm install' on the '${currentPlatformId}' platform.`);
            ^

Error: 'linux-x64' binaries cannot be used on the 'linuxmusl-x64' platform. Please remove the 'node_modules/sharp' directory and run 'npm install' on the 'linuxmusl-x64' platform.
    at Object.hasVendoredLibvips (/usr/app/node_modules/sharp/lib/libvips.js:82:13)
    at Object.<anonymous> (/usr/app/node_modules/sharp/lib/constructor.js:7:22)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/usr/app/node_modules/sharp/lib/index.js:3:15)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/usr/app/node_modules/image-thumbnail/src/index.js:6:15)

![스크린샷, 2021-09-30 00-38-57](https://user-images.githubusercontent.com/6076067/135302319-53c8eb77-00ec-4733-8ca0-836d6f704620.png)

**Comment by WilliamFariasDev** [comment]
I forked, changed the sharp to lastest version (v0.29.1) on package.json and worked!

**Comment by heoyongun** [comment]
> I forked, changed the sharp to lastest version (v0.29.1) on package.json and worked!

Thank you.


https://github.com/lovell/sharp/issues/2312

> The architecture and platform of Node.js used for npm install must be the same as the architecture and platform of Node.js used at runtime.

interim measure, like this.
> npm i --arch=x64 --platform=linuxmusl

work for me.

**Comment by onildoaguiar** [comment]
Thanks @heoyongun @WilliamFariasDev 

Sharp version upgraded to 0.30.4:
https://github.com/onildoaguiar/image-thumbnail/blob/master/package.json#L33
