### ISSUE TITLE
Does the Package work in serverless environment ?

### ISSUE THREAD

**Issue by saurav2799** [onildoaguiar/image-thumbnail#74]
Hi, 

I installed the package on a serverless environment and getting the following error at runtime.
Could you please advise if this would work ?

Thank You. 

```
> error: 
failed to execute source for 'node_modules/image-thumbnail/index.js': FunctionError: failed to execute source for 'node_modules/image-thumbnail/src/index.js': FunctionError: failed to execute source for 'node_modules/sharp/lib/index.js': FunctionError: failed to execute source for 'node_modules/sharp/lib/constructor.js': Error: 
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp.node'

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose sharp" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

	at node_modules/sharp/lib/constructor.js:39:9(140)

	at require (native)
	at node_modules/sharp/lib/index.js:11:21(15)

	at require (native)
	at node_modules/image-thumbnail/src/index.js:25:21(38)

	at require (native)
	at node_modules/image-thumbnail/index.js:11:26(15)


```

**Comment by onildoaguiar** [comment]
This package is server-side only, you will need a node and extras libs from sharp dependencies.
